on:
  push:
    branches:
      - master
  schedule:
    - cron: "0 0 * * *"

name: Branch push received

jobs:
  build:
    name: Create branch release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get todays date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"
        id: date

      - name: Run string replace
        uses: frabert/replace-string-action@master
        id: format-time
        with:
          pattern: '[:\.]+'
          string: "${{ steps.date.outputs.date }}"
          replace-with: "."
          flags: "g"

      - id: next_version
        uses: zwaldowski/semver-release-action@v1
        with:
          dry_run: true
          bump: ${{ … }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Create release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: "${{ steps.next_version.outputs.version }}"
          release_name: Release "${{ steps.next_version.outputs.version }}"
          draft: false
          prerelease: false